@url = http://localhost:8080/api/collection

// find()
GET {{url}} HTTP/1.1

###
// find()
GET {{url}}/1 HTTP/1.1

###

// add()
POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "My Collection",
    "characters": []
}

###

DELETE {{url}}/2 HTTP/1.1